services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Construct DATABASE_URL from .env with safe defaults to avoid warnings
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app}"
      NODE_ENV: ${NODE_ENV:-development}^
      APP_PORT: ${APP_PORT:-3000}
      RESEND_API_KEY: ${RESEND_API_KEY}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      ADMIN_MANAGEMENT_KEY: ${ADMIN_MANAGEMENT_KEY}
      DEBUG_SECURE_MW: ${DEBUG_SECURE_MW:-0}
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3000}:3000"
      - "${SIO_PORT:-3100}:3100"

volumes:
  db_data: {}
